name: release

on:
  push:
    tags:
      - "v*.*"

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Update version number
      run: sed -i 's?DEV-VERSION-0.0?${{ github.ref_name }}?' cmd/root.go

    - name: Build
      run: go build

    - name: Zip artifact for deployment
      run: zip vaxctl_${{ github.ref_name }}_linux_amd64.zip ./vaxctl

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        generate_release_notes: true
        files: vaxctl_${{ github.ref_name }}_linux_amd64.zip

  build-macos:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Update version number
      run: sed -i '' 's?DEV-VERSION-0.0?${{ github.ref_name }}?' cmd/root.go

    - name: Build
      run: go build

    - name: Zip artifact for deployment
      run: zip vaxctl_${{ github.ref_name }}_darwin_amd64.zip ./vaxctl

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        generate_release_notes: true
        files: vaxctl_${{ github.ref_name }}_darwin_amd64.zip
